// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Session struct {
	ID        int64
	UserID    int64
	Token     string
	CreatedAt time.Time
}

type User struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

type UserBodyFatPercentage struct {
	UserID            int64
	BodyFatPercentage float64
	CreatedAt         time.Time
}

type UserCaloricIntake struct {
	UserID        int64
	CaloricIntake float64
	CreatedAt     time.Time
}

type UserWeight struct {
	UserID    int64
	Weight    float64
	CreatedAt time.Time
}
