// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, db DBTX, arg CreateSessionParams) (int64, error)
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (int64, error)
	DeleteSession(ctx context.Context, db DBTX, token string) error
	GetUserByEmailAndPassword(ctx context.Context, db DBTX, arg GetUserByEmailAndPasswordParams) (User, error)
	JoinSessionByUserId(ctx context.Context, db DBTX, token string) (JoinSessionByUserIdRow, error)
	// SQLite3 queries.
	// All queries should be idempotent.
	Ping(ctx context.Context, db DBTX) (int64, error)
}

var _ Querier = (*Queries)(nil)
