// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token) VALUES (?, ?) RETURNING id
`

type CreateSessionParams struct {
	UserID int64
	Token  string
}

func (q *Queries) CreateSession(ctx context.Context, db DBTX, arg CreateSessionParams) (int64, error) {
	row := db.QueryRowContext(ctx, createSession, arg.UserID, arg.Token)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash) VALUES (?, ?, ?) RETURNING id
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (int64, error) {
	row := db.QueryRowContext(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUserWeight = `-- name: CreateUserWeight :exec
INSERT INTO user_weight (user_id, weight, created_at) VALUES (?, ?, ?)
`

type CreateUserWeightParams struct {
	UserID    int64
	Weight    float64
	CreatedAt time.Time
}

func (q *Queries) CreateUserWeight(ctx context.Context, db DBTX, arg CreateUserWeightParams) error {
	_, err := db.ExecContext(ctx, createUserWeight, arg.UserID, arg.Weight, arg.CreatedAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, db DBTX, token string) error {
	_, err := db.ExecContext(ctx, deleteSession, token)
	return err
}

const getUserByEmailAndPassword = `-- name: GetUserByEmailAndPassword :one
SELECT id, name, email, password_hash, created_at FROM users WHERE email = ? AND password_hash = ? LIMIT 1
`

type GetUserByEmailAndPasswordParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) GetUserByEmailAndPassword(ctx context.Context, db DBTX, arg GetUserByEmailAndPasswordParams) (User, error) {
	row := db.QueryRowContext(ctx, getUserByEmailAndPassword, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWeightHistory = `-- name: GetUserWeightHistory :many
SELECT user_id, weight, created_at FROM user_weight WHERE user_id = ?
`

func (q *Queries) GetUserWeightHistory(ctx context.Context, db DBTX, userID int64) ([]UserWeight, error) {
	rows, err := db.QueryContext(ctx, getUserWeightHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserWeight
	for rows.Next() {
		var i UserWeight
		if err := rows.Scan(&i.UserID, &i.Weight, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinSessionByUserId = `-- name: JoinSessionByUserId :one
SELECT sessions.id, user_id, token, sessions.created_at, users.id, name, email, password_hash, users.created_at FROM sessions JOIN users ON sessions.user_id = users.id WHERE sessions.token = ? LIMIT 1
`

type JoinSessionByUserIdRow struct {
	ID           int64
	UserID       int64
	Token        string
	CreatedAt    time.Time
	ID_2         int64
	Name         string
	Email        string
	PasswordHash string
	CreatedAt_2  time.Time
}

func (q *Queries) JoinSessionByUserId(ctx context.Context, db DBTX, token string) (JoinSessionByUserIdRow, error) {
	row := db.QueryRowContext(ctx, joinSessionByUserId, token)
	var i JoinSessionByUserIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ID_2,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt_2,
	)
	return i, err
}

const ping = `-- name: Ping :one

SELECT 1
`

// SQLite3 queries.
// All queries should be idempotent.
func (q *Queries) Ping(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRowContext(ctx, ping)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
